/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Blog nestjs API
 * Blog 개발을 위한 nestjs api 문서입니다
 * OpenAPI spec version: 1.0
 */
import type { GithubUserInfoDTO } from './githubUserInfoDTO';
import type { GithubSignUpDtoPositionType } from './githubSignUpDtoPositionType';

export type GithubSignUpDto = {
  /** github User Data Type */
  githubUserInfo: GithubUserInfoDTO;
  /** 개발자 포지션 타입 */
  positionType: GithubSignUpDtoPositionType;
};
