/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Blog nestjs API
 * Blog 개발을 위한 nestjs api 문서입니다
 * OpenAPI spec version: 1.0
 */

/**
 * 개발 포지션 타입
 */
export type LocalSignUpRequestDtoPositionType = { [key: string]: any };
