/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Blog nestjs API
 * Blog 개발을 위한 nestjs api 문서입니다
 * OpenAPI spec version: 1.0
 */

/**
 * 개발 포지션 타입
 */
export type UserDtoPositionType = typeof UserDtoPositionType[keyof typeof UserDtoPositionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserDtoPositionType = {
  'Front-End': 'Front-End',
  'Back-End': 'Back-End',
  'Full-Stack': 'Full-Stack',
} as const;
