/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Blog nestjs API
 * Blog 개발을 위한 nestjs api 문서입니다
 * OpenAPI spec version: 1.0
 */
import type { UserDtoPositionType } from './userDtoPositionType';
import type { UserDtoLoginType } from './userDtoLoginType';
import type { UserDtoRole } from './userDtoRole';

export type UserDto = {
  /** Primary key ID */
  id: number;
  /** githubID */
  githubID: number;
  /** 이메일 */
  email: string;
  /** 닉네임 */
  nickname: string;
  /** loginID */
  loginID: string;
  /** blog url */
  blog: string;
  /** 자기소개 */
  bio: string;
  /** 프로필 사진 url */
  avatarUrl: string;
  /** Github url */
  githubPageUrl: string;
  /** 개발 포지션 타입 */
  positionType: UserDtoPositionType;
  /** 로그인 type */
  loginType: UserDtoLoginType;
  /** user의 권한 */
  role: UserDtoRole;
  /** 가입 일자 */
  createdAt: string;
  /** 수정 일자 */
  updatedAt: string;
  /** 탈퇴 일자 */
  deletedAt: string;
};
